"""second migration

Revision ID: 788d10c2bf99
Revises: 3cab2d867946
Create Date: 2018-06-22 15:59:13.763890

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '788d10c2bf99'
down_revision = '3cab2d867946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('date', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
